### ISSUE TITLE
求助：显存占用过高的问题

### ISSUE THREAD

**Issue by chimeraliu** [zhangnengwei123/vLLM#1]
先说一下环境 cuda 10.0 torch2.3.1+cu12.1 transformer 4.42.4
部署的是qwen2-7B
运行dokcer+vllm时显存占用28G，并且推理效果不是很好，您知道是哪里出问题了吗

**Comment by zhangnengwei123** [comment]
这里给您提供一个排查问题的思路。
显存占用28G，猜测是模型加载了两次，建议使用nvidia-smi观察显存使用情况，在docker服务关闭然后启动过程中去观察一下。
推理效果不好的问题，建议您先单独运行qwen2-7B，看看效果。再结合vLLM看看效果。

**Comment by chimeraliu** [comment]
补充信息有两个进程分别占用了14G显存 一个是python3进程一个是rayray::RayWorkerVllm 这样加起来是占用了28G显存，请问您在模型部署时的显存占用情况是怎样的呢

**Comment by chimeraliu** [comment]
补充信息：
有两个进程分别占用了14G显存 一个是python3进程一个是rayray::RayWorkerVllm
这样加起来是占用了28G显存
请问您在模型部署时的显存占用情况是怎样的呢

**Comment by chimeraliu** [comment]
补充信息：
有两个进程分别占用了14G显存 一个是python3进程一个是ray::RayWorkerVllm
这样加起来是占用了28G显存
请问您在模型部署时的显存占用情况是怎样的呢
